import type {Metadata} from "next";
import RootProvider from "./_components/_provider/RootProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <RootProvider>{children}</RootProvider>
        <div id="quiz"></div>
        <div id="loading"></div>
      </body>
    </html>
  );
}
